"""Canonical contracts for the first HamidCognition awareness tree."""
from .awareness_layer import AwarenessContract,ActionPermission,ActionMode,Maturity

def canonical_contracts():
    return [
        AwarenessContract("GOVERNANCE","ROOT","Maintain system-wide safety, evidence and authority boundaries",Maturity.SPECIFIED,("policy","permissions","evidence"),("violation","missing_evidence"),("audit","escalate"),("cannot self-grant authority",),(ActionPermission("audit",ActionMode.EXECUTE),ActionPermission("escalate",ActionMode.ESCALATE)),"HUMAN_APPROVAL"),
        AwarenessContract("COGNITION","ROOT","Maintain self, creator-context, market and reasoning models",Maturity.PROTOTYPE,("model_staleness","knowledge_gaps"),("stale_model","unknown"),("research","update_model"),("cannot invent evidence",),(ActionPermission("research",ActionMode.EXECUTE),ActionPermission("update_model",ActionMode.PROPOSE)),"GOVERNANCE"),
        AwarenessContract("EXECUTION","ROOT","Coordinate prompts, modules, tools and workflows",Maturity.PROTOTYPE,("task_state","tool_state"),("blocked_task","authorized_task"),("run_prompt","run_module","invoke_tool"),("cannot bypass authority",),(ActionPermission("run_prompt",ActionMode.EXECUTE),ActionPermission("run_module",ActionMode.EXECUTE),ActionPermission("invoke_tool",ActionMode.EXECUTE)),"GOVERNANCE"),
        AwarenessContract("FEEDBACK","ROOT","Verify actions and feed results into state",Maturity.SPECIFIED,("results","evidence"),("failed_action","missing_proof"),("verify","record"),("cannot declare unsupported success",),(ActionPermission("verify",ActionMode.EXECUTE),ActionPermission("record",ActionMode.EXECUTE)),"GOVERNANCE"),
        AwarenessContract("SELF-MODEL","COGNITION","Track implemented capabilities and their evidence",Maturity.PROTOTYPE,("capability_ledger","test_results"),("stale_capability","failed_test"),("refresh_capability"),("cannot upgrade maturity without evidence",),(ActionPermission("refresh_capability",ActionMode.PROPOSE),),"COGNITION"),
        AwarenessContract("CREATOR-CONTEXT","COGNITION","Track explicit project goals, constraints and decisions",Maturity.PROTOTYPE,("project_context","decisions"),("context_gap","contradiction"),("record_context"),("no sensitive inference",),(ActionPermission("record_context",ActionMode.PROPOSE),),"COGNITION"),
        AwarenessContract("MARKET-INTELLIGENCE","COGNITION","Maintain dated market evidence and counter-evidence",Maturity.PROTOTYPE,("sources","market_signals"),("stale_source","new_signal"),("research_market","record_signal"),("no invented demand",),(ActionPermission("research_market",ActionMode.EXECUTE),ActionPermission("record_signal",ActionMode.PROPOSE)),"COGNITION"),
        AwarenessContract("REASONING","COGNITION","Transform verified evidence into bounded inferences",Maturity.PROTOTYPE,("evidence","assumptions"),("evidence_change","contradiction"),("recompute"),("must separate fact from inference",),(ActionPermission("recompute",ActionMode.EXECUTE),),"COGNITION"),
        AwarenessContract("PROMPTS","EXECUTION","Run prompt assets under explicit contracts",Maturity.PROTOTYPE,("prompt_state","inputs"),("task_ready","input_gap"),("run_prompt"),("no hidden privilege escalation",),(ActionPermission("run_prompt",ActionMode.EXECUTE),),"EXECUTION"),
        AwarenessContract("MODULES","EXECUTION","Run deterministic application modules",Maturity.PROTOTYPE,("module_state","inputs"),("task_ready","module_failure"),("run_module"),("no self-modification of authority",),(ActionPermission("run_module",ActionMode.EXECUTE),),"EXECUTION"),
        AwarenessContract("TOOLS","EXECUTION","Invoke external capabilities through bounded interfaces",Maturity.SPECIFIED,("tool_state","permissions"),("tool_needed","permission_gap"),("invoke_tool"),("no credential disclosure",),(ActionPermission("invoke_tool",ActionMode.EXECUTE),),"EXECUTION"),
        AwarenessContract("WORKFLOWS","EXECUTION","Coordinate multi-step operations",Maturity.PROTOTYPE,("workflow_state","dependencies"),("blocked_step","dependency_ready"),("advance_workflow"),("cannot skip approval gates",),(ActionPermission("advance_workflow",ActionMode.EXECUTE),),"EXECUTION"),
        AwarenessContract("VERIFICATION","FEEDBACK","Check claims and actions against evidence",Maturity.VERIFIED,("claims","artifacts","tests"),("claim_without_evidence","test_failure"),("verify"),("cannot manufacture proof",),(ActionPermission("verify",ActionMode.EXECUTE),),"FEEDBACK"),
        AwarenessContract("MEMORY","FEEDBACK","Persist verified state and provenance",Maturity.PROTOTYPE,("records","provenance"),("new_verified_fact","conflict"),("record"),("cannot overwrite provenance silently",),(ActionPermission("record",ActionMode.EXECUTE),),"FEEDBACK"),
        AwarenessContract("LEARNING","FEEDBACK","Convert verified outcomes into model updates",Maturity.PROTOTYPE,("outcomes","errors"),("new_evidence","repeated_failure"),("update"),("no learning from unverified claims",),(ActionPermission("update",ActionMode.PROPOSE),),"FEEDBACK"),
    ]
